### PR TITLE
Api extension - Authenticate

### PR DESCRIPTION
**Pull request by Isigiel**
To authenticate POST `email` and `password` to `/api/login`. The app will then return `200` and session as well as remeber cookies if login was successful or `403` if there was an error.
First step for @Zlepper and #414

### CODE REVIEW

**Comment by zlepper** [comment]
Not exactly first step, but it should allow me to integrate most of the functionality of Solder into Solderhelper. 

It's also bad style for an API to use cookies, but it's a temporary workaround until there is a proper API in place.

**Comment by Isigiel** [comment]
I agree on the cookies and would suggest the use of json web tokens for future api authentication

**Comment by sct** [comment]
You don't need a special API endpoint for this. You can just post to the current login of Solder and get the exact same result?

**Comment by zlepper** [comment]
Problem is that always return 200, and then an html page. Which makes it reallt hard to figure out if the login request was successful. At least I haven't found ant easy way to read it from what is currently possible.

**Comment by sct** [comment]
Then why don't we change the login page to return a 401 on failed logins?

**Comment by zlepper** [comment]
Would work just as well

**Pull request closed without merging**
