### PR TITLE
Create LimitChecker.php

### PR DESCRIPTION
**Pull request by FlareHAX0R**
Check the webserver for limits.
This checks for php safemode/basedir and if shell_exec is enabled
(This is untested)

### CODE REVIEW

**Comment by TheDoctorsLife** [comment]
I looked it over, should work, But since I don't write php I won't know.

**Comment by FlareHAX0R** [comment]
If your wondering "What's the purpose of this", it could be very useful incase 1/2 click updates are added/readded.

**Comment by GenPage** [comment]
Will need to fully test this out before I accept it.

**Comment by FlareHAX0R** [comment]
Ok. I'll also test it.

**Comment by FlareHAX0R** [comment]
It seems to work. It returned "false::false" on the webserver I tested it on.

**Comment by FlareHAX0R** [comment]
Is this gonna be merged?

**Comment by GenPage** [comment]
No longer needed as the Updater has been scrapped.

**Pull request closed without merging**
