### PR TITLE
Make it possible to create a pack that is visible at creation

### PR DESCRIPTION
**Pull request by zlepper**
Another thing I need for solderhelper to work without hacks before the api is done. 
It keeps the current functionality where packs are created as hidden by the user, but you can send an additional parameter to the body and the pack will become visible.

### CODE REVIEW

**Comment by Isigiel** [comment]
Does this also work if `hidden`is missing from the input soesn't have the field?

**Comment by zlepper** [comment]
It checks for a truthy value, so it should

**Comment by GenPage** [comment]
LGTM :shipit:

**Comment by zlepper** [comment]
Whoop whoop, only one pr left and I can stop using a site scrapper to interact with solder !

**Pull request merged**
