### PR TITLE
Return list of mods when /api/mod is called.

### PR DESCRIPTION
**Pull request by Indemnity83**
This addresses issue #393

### CODE REVIEW

**Comment by GenPage** [comment]
Solid commit, can you change it to reflect the same behavior as /api/modpack. We dont need all that info in the listing, just the mod name and its pretty_name so you can then pull the full mod info from /api/mod/:name

Example:
```
$response['mods'][$mod->name] = $mod-> pretty_name;
```

**Comment by Indemnity83** [comment]
Very good point, updated!

**Comment by Indemnity83** [comment]
Squashed and rebased for changes on dev branch

**Comment by GenPage** [comment]
:+1: :shipit:

**Pull request merged**
