### PR TITLE
fix travis testing

### PR DESCRIPTION
**Pull request by skwerlman**
see #584
(thanks @daemonnecis)

### CODE REVIEW

**Comment by skwerlman** [comment]
I am unsure why 223.4 failed, but it does not seem related to this pr. (besides, it worked from my fork: https://travis-ci.org/skwerlman/TechnicSolder/builds/142911636)

**Comment by aschmois** [comment]
Travis testing is broken because of a broken php config (timezone issue), not fixable by code.

**Comment by skwerlman** [comment]
Look at the actual tests. All but one job passes now, and the one that doesn't is because of an unrelated, apparently transient, issue.

**Comment by GenPage** [comment]
@skwerlman This is actually redundant and covers up the real issue, but I appreciate the PR <3

@daemonnecis touches on this: https://github.com/TechnicPack/TechnicSolder/issues/584#issuecomment-230935396

Travis already runs "composer install", and there is code in the composer.json to copy the config. The debugging needs to happen here:

https://github.com/TechnicPack/TechnicSolder/blob/master/composer.json#L47

Most likely the issue is with checking the "PHP_OS" string var. As it was an attempt to support Windows since the command is instead `copy`. I'm all for removing that functionality and proceeding with just the `cp` command since Windows is not officially supported.

**Comment by GenPage** [comment]
@skwerlman I see you are attempting to fix this, I would just recommend re-adding the "cp -R app/config-sample app/config" that was removed here:

https://github.com/TechnicPack/TechnicSolder/pull/591/commits/a4d3b675d604701480077860e9e45c126301714d#diff-354f30a63fb0907d4ad57269548329e3L40

**Comment by skwerlman** [comment]
Reverted to original fix

**Pull request merged**
