### PR TITLE
Add growl alerts

### LINKED ISSUE #144: Feature Request: Move green notification zone up higher
As it stands now when you change a mod, or property on a modpack at the versions screen a green notifier bubble appears at the top of the page and moves everything down one or two until it fades off and then everything slides back into place.

Either make the bubble truly float on the page or move it into a block that is more static. For instance right after the words "Modpack Management"
update bubbles

The other place where it should be moved is at the Modpack Management screen. I suggest again moving the update bubble so that it appears right after the words "Modpack Management", or make it a true floater.
update bubbles 2

### PR DESCRIPTION
**Pull request by Indemnity83**
Fixes #144 and #239

Changes the popup alerts to jGrowl alerts that load as overlays in the top right of the screen in a queue.

### CODE REVIEW

**Comment by skwerlman** [comment]
looks like #446 wound up in here

**Comment by Indemnity83** [comment]
Yeah, I borked up the commits trying to make sure that tests passed.

**Comment by GenPage** [comment]
I pulled the test cases in first along with your other commits that didn't conflict. 

Can you rebase and resubmit this one? Thanks!

**Comment by Indemnity83** [comment]
Cleaned up the commits, should be a clean merge now.

**Comment by Indemnity83** [comment]
Squashed and rebased against changes to dev

**Comment by GenPage** [comment]
Looks good so far, just need to checkout the branch to check in my dev environment! I plan on doing this tomorrow

**Comment by GenPage** [comment]
:+1: :shipit:

**Pull request merged**
